"""
TreeMetadataRepository - Handles CRUD operations for tree metadata.
"""

import threading
from typing import List, Optional
from uuid import UUID

from features.tree.models.tree import Tree
from infrastructure.database.supabase_service import SupabaseService
from utils.logger import logger


class TreeMetadataRepository:
    """
    Repository for managing tree metadata in the database.

    Handles CRUD operations for the 'trees' table, providing methods to
    create, read, update, and delete tree metadata records.
    """

    def __init__(self, supabase_service: SupabaseService):
        """Initialize the repository with a Supabase service."""
        self.client = supabase_service.get_client()
        self.table_name = "trees"
        self._lock = threading.Lock()
        logger.info("TreeMetadataRepository initialized.")

    def create_tree(self, tree: Tree) -> Optional[Tree]:
        """
        Create a new tree in the database.

        Args:
            tree: Tree instance to create (id will be generated by database)

        Returns:
            Tree instance with populated id and timestamps, or None if creation failed
        """
        with self._lock:
            try:
                # Prepare data for insertion (exclude id, created_at, updated_at - they're auto-generated)
                insert_data = {
                    "name": tree.name,
                    "topic": tree.topic,
                    "description": tree.description,
                    "root_node_id": tree.root_node_id,
                }

                response = (
                    self.client.table(self.table_name).insert(insert_data).execute()
                )

                if response.data:
                    created_tree = Tree.from_dict(response.data[0])
                    logger.info(
                        f"Created tree: {created_tree.name} (ID: {created_tree.id})"
                    )
                    return created_tree

                logger.error("No data returned from tree creation")
                return None

            except Exception as e:
                logger.error(f"Error creating tree '{tree.name}': {e}")
                return None

    def get_tree(self, tree_id: UUID) -> Optional[Tree]:
        """
        Retrieve a tree by its ID.

        Args:
            tree_id: UUID of the tree to retrieve

        Returns:
            Tree instance if found, None otherwise
        """
        try:
            response = (
                self.client.table(self.table_name)
                .select("*")
                .eq("id", str(tree_id))
                .execute()
            )

            if response.data:
                tree = Tree.from_dict(response.data[0])
                logger.debug(f"Retrieved tree: {tree.name} (ID: {tree_id})")
                return tree

            logger.debug(f"Tree with ID {tree_id} not found")
            return None

        except Exception as e:
            logger.error(f"Error retrieving tree {tree_id}: {e}")
            return None

    def get_tree_by_name(self, name: str) -> Optional[Tree]:
        """
        Retrieve a tree by its name.

        Args:
            name: Name of the tree to retrieve

        Returns:
            Tree instance if found, None otherwise
        """
        try:
            response = (
                self.client.table(self.table_name)
                .select("*")
                .eq("name", name)
                .execute()
            )

            if response.data:
                tree = Tree.from_dict(response.data[0])
                logger.debug(f"Retrieved tree by name: {tree.name}")
                return tree

            logger.debug(f"Tree with name '{name}' not found")
            return None

        except Exception as e:
            logger.error(f"Error retrieving tree by name '{name}': {e}")
            return None

    def list_trees(self, limit: Optional[int] = None) -> List[Tree]:
        """
        List all trees in the database.

        Args:
            limit: Optional limit on number of trees to return

        Returns:
            List of Tree instances, ordered by creation date (newest first)
        """
        try:
            query = (
                self.client.table(self.table_name)
                .select("*")
                .order("created_at", desc=True)
            )

            if limit:
                query = query.limit(limit)

            response = query.execute()

            trees = [Tree.from_dict(tree_data) for tree_data in response.data or []]
            logger.debug(f"Retrieved {len(trees)} trees from database")
            return trees

        except Exception as e:
            logger.error(f"Error listing trees: {e}")
            return []

    def update_tree(self, tree_id: UUID, updates: dict) -> Optional[Tree]:
        """
        Update a tree's metadata.

        Args:
            tree_id: UUID of the tree to update
            updates: Dictionary of fields to update

        Returns:
            Updated Tree instance if successful, None otherwise
        """
        with self._lock:
            try:
                # Filter out None values and non-updatable fields
                allowed_fields = {"name", "topic", "description", "root_node_id"}
                filtered_updates = {
                    k: v
                    for k, v in updates.items()
                    if k in allowed_fields and v is not None
                }

                if not filtered_updates:
                    logger.warning(f"No valid updates provided for tree {tree_id}")
                    return self.get_tree(tree_id)

                response = (
                    self.client.table(self.table_name)
                    .update(filtered_updates)
                    .eq("id", str(tree_id))
                    .execute()
                )

                if response.data:
                    updated_tree = Tree.from_dict(response.data[0])
                    logger.info(f"Updated tree: {updated_tree.name} (ID: {tree_id})")
                    return updated_tree

                logger.error(f"No data returned from tree update for ID {tree_id}")
                return None

            except Exception as e:
                logger.error(f"Error updating tree {tree_id}: {e}")
                return None

    def delete_tree(self, tree_id: UUID) -> bool:
        """
        Delete a tree from the database.

        Note: This will also delete all associated nodes due to CASCADE constraint.

        Args:
            tree_id: UUID of the tree to delete

        Returns:
            True if deletion was successful, False otherwise
        """
        with self._lock:
            try:
                response = (
                    self.client.table(self.table_name)
                    .delete()
                    .eq("id", str(tree_id))
                    .execute()
                )

                # Check if any rows were affected
                if response.data is not None:
                    logger.info(f"Successfully deleted tree with ID: {tree_id}")
                    return True

                logger.warning(f"No tree found with ID {tree_id} to delete")
                return False

            except Exception as e:
                logger.error(f"Error deleting tree {tree_id}: {e}")
                return False

    def tree_exists(self, tree_id: UUID) -> bool:
        """
        Check if a tree exists in the database.

        Args:
            tree_id: UUID of the tree to check

        Returns:
            True if tree exists, False otherwise
        """
        return self.get_tree(tree_id) is not None

    def name_exists(self, name: str, exclude_tree_id: Optional[UUID] = None) -> bool:
        """
        Check if a tree name already exists in the database.

        Args:
            name: Name to check for uniqueness
            exclude_tree_id: Optional tree ID to exclude from the check (for updates)

        Returns:
            True if name exists, False otherwise
        """
        try:
            query = self.client.table(self.table_name).select("id").eq("name", name)

            if exclude_tree_id:
                query = query.neq("id", str(exclude_tree_id))

            response = query.execute()
            return len(response.data or []) > 0

        except Exception as e:
            logger.error(f"Error checking name existence '{name}': {e}")
            return False
